name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest black isort flake8 pylint bandit
          if (Test-Path requirements.txt) { pip install --upgrade -r requirements.txt }

      - name: Update Python Packages
        run: |
          pip list --outdated --format=json | jq -r '.[] | .name' | xargs pip install --upgrade

      - name: Run tests
        run: pytest || echo "Tests failed, but workflow continues."

      - name: Run formatting & linting
        run: |
          black . || echo "Black formatting issues detected."
          isort . || echo "Import sorting issues detected."
          flake8 . || echo "Linting issues detected."

      - name: Run Code Analysis
        run: |
          pylint $(git ls-files '*.py') || echo "Pylint issues detected."
          bandit -r . || echo "Security issues detected."
